### ISSUE TITLE
pip aiida-gaussian installation error

### ISSUE THREAD

**Issue by kmlefran** [nanotech-empa/aiida-gaussian#36]
Installing aiida-gaussian with

`pip install aiida-gaussian`

Results in the following error. Other aiida plugins, e.g. aiida-quantumespresso install without issue.

Operating system: Mac OS Ventura 13.5.1

## Package versions installed that seem to be referenced in below error:

pymatgen                  2023.8.10

cython                    3.0.2

numpy                     1.25.2 

Can anyone assist? Thanks

## Error message

```
/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/Cython/Compiler/Main.py:384: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-install-p8qddv0z/pymatgen_7873d81d50194771b0d801f8d02c3cec/pymatgen/optimization/linear_assignment.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      Compiling pymatgen/optimization/linear_assignment.pyx because it changed.
      [1/1] Cythonizing pymatgen/optimization/linear_assignment.pyx
      building 'pymatgen.optimization.linear_assignment' extension
      creating build/temp.macosx-11.0-arm64-cpython-311
      creating build/temp.macosx-11.0-arm64-cpython-311/pymatgen
      creating build/temp.macosx-11.0-arm64-cpython-311/pymatgen/optimization
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/chemlab/anaconda3/envs/aiida/include -arch arm64 -fPIC -O2 -isystem /Users/chemlab/anaconda3/envs/aiida/include -arch arm64 -I/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/numpy/core/include -I/Users/chemlab/anaconda3/envs/aiida/include/python3.11 -c pymatgen/optimization/linear_assignment.c -o build/temp.macosx-11.0-arm64-cpython-311/pymatgen/optimization/linear_assignment.o
      In file included from pymatgen/optimization/linear_assignment.c:1167:
      In file included from /private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/numpy/core/include/numpy/arrayobject.h:5:
      In file included from /private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
      In file included from /private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/numpy/core/include/numpy/ndarraytypes.h:1948:
      /private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
warning: pymatgen/util/coord_cython.pyx:214:25: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
      warning: pymatgen/util/coord_cython.pyx:263:41: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          #ensure correct shape
          fcoords1, fcoords2 = np.atleast_2d(fcoords1, fcoords2)
      
          pbc = lattice.pbc
          cdef int n_pbc = sum(pbc)
          cdef int n_pbc_im = 3 ** n_pbc
                                ^
      ------------------------------------------------------------
      
      pymatgen/util/coord_cython.pyx:91:26: Cannot assign type 'double' to 'int'
      Compiling pymatgen/util/coord_cython.pyx because it changed.
      [1/1] Cythonizing pymatgen/util/coord_cython.pyx
      Traceback (most recent call last):
        File "/Users/chemlab/anaconda3/envs/aiida/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/chemlab/anaconda3/envs/aiida/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/chemlab/anaconda3/envs/aiida/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 72, in <module>
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/normal/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
          new_ext = cythonize(
                    ^^^^^^^^^^
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/ym/y0s4kqzn6jzg2sklwl15xzjm0000gr/T/pip-build-env-hcrp_pb6/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: pymatgen/util/coord_cython.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymatgen
Failed to build pymatgen
ERROR: Could not build wheels for pymatgen, which is required to install pyproject.toml-based projects
```

**Comment by kmlefran** [comment]
Manually installing dependencies to the correct acceptable versions (pymatgen 2022.11.7, cclib 1.6.3, ase, aiida-core 2.4.0) fixed the issue. The issue was with the pip install of pymatgen likely. Installing pymatgen version with Conda should be sufficient to not see this issue.

**Comment by eimrek** [comment]
Great that you got this working 👍 Good luck with the plugin! feel free to open any new issues if you run into any other problems.
